### ISSUE TITLE
All panels fail in 500 error

### ISSUE THREAD

**Issue by boydspace** [Acme-Plugins/MassWhitelist#1]
Installed following your directions but when I login, I receive a 500 error no matter what I do. I have php 7.0, MySQL 7. I have everything setup in an Ubuntu server. I have a domain name setup. I have the domain pointed to the correct place, etc. But I keep getting a 500 error. Let me know what more information you need! Thanks!

**Comment by konsyr11** [comment]
Hello! Thanks for getting the plugin! The only time I have seen an error 500 during testing was when the panel could not connect to the database. Assuming you downloaded the latest panel and plugin versions, have you completed database initialization?

**Comment by konsyr11** [comment]
Did you manage to fix the problem?

**Comment by boydspace** [comment]
Alas, no. The database is connecting just fine. Ive tried also changing it from localhost to 127.0.0.1, to the public IP of the server, to the domain name all with no luck. It seems to connect because I can go to the register page directly and create an account once logged in, but I cannot access the index page.

Default admin account is setup from your instructions:

https://shenanigans.world/masswhitelist/index.php <https://shenanigans.world/masswhitelist/index.php>

Any help would be greatly appreciated!

**Comment by konsyr11** [comment]
Let me load up a fresh installation on my test webserver real quick. Sorry for the inconvenience!

**Comment by boydspace** [comment]
No worries! And sorry I didn’t respond sooner! Been a crazy couple days! Your response time is also extremely amazing!!

**Comment by konsyr11** [comment]
Hey, first of all thanks, I have setup GitHub to send me a message on Discord whenever something happens so I can respond fast.
I just uploaded a brand new download on my webserver, and it works just fine. So it is not a problem with the panel in general. Now let's start eliminating problems.
Can you try redownloading the ZIP and replacing the index.html? Just in case something got corrupted, or maybe you accidentally deleted something like a quotation mark?

**Comment by boydspace** [comment]
No dice. I replaced everything and recreated the config file. Still tossing a 500 error once I login.

**Comment by boydspace** [comment]
When you setup your test server, what are you running exactly? You running it in WAMP, or an actual server setup such as linux?

**Comment by konsyr11** [comment]
I am running it on a hosting provider, I am gonna test it on an Ubuntu server tomorrow. So if you could give some more information about your setup, such as MySQL and PHP version etc, I can try recreate the problem. Are you using apache or nginx? It shouldn't make any difference really, just to be covered.

**Comment by konsyr11** [comment]
I really cannot explain why only index does that, whereas everything else works. Except if I am missing something very simple, such as a php extension that I should have put in Requirements.

**Comment by boydspace** [comment]
I’m using apache2, I have tried php 7.0, 7.2, and 7.4, I am using 10.1.44-MariaDB-0ubuntu0.18.04.1.

**Comment by konsyr11** [comment]
I managed to recreate the problem with a simple installation of a LAMP stack, without any PHP extensions and plugins. So I believe that I just forgot to write down the PHP extensions needed for it to work. I am gonna let you know soon!

**Comment by konsyr11** [comment]
Hello, the problem is addressed and I will be making changes to the code and pushing updates soon. I will also fix some other bugs in this update. The problem was a bit of a weird one. I am using MySQL functions in some places of the code, instead of MySQLi. In my hosting service they have modified PHP so that MySQL works in all PHP versions, whereas MySQL was deceprated in PHP 5.5 and completely removed in 7.0. If you want a quicker fix than waiting for me to push the update (within this week), you can downgrade to PHP 5.4.
By the way, for quicker support, you can join our [Discord server](https://discord.acmeplugins.cf/).

**Comment by konsyr11** [comment]
Hey, just released version 1.2 of the plugin and web interfaces, that fix this bug and add some more features. Download [here](https://github.com/Acme-Plugins/MassWhitelist/releases/1.2). You need to update both the interfaces and the plugin for this to work, as I have made some changes to the table structure. Let me know if it is still not working, or close the issue :)

**Comment by boydspace** [comment]
Thank you! The new version fixes everything!
